baseURL = "https://dgraph-twitter-clone-tutorial.netlify.com/"
languageCode = "en-us"
title = "Dgraph Twitter Clone Tutorial"
theme = "hugo-docs"

[[menu.main]]
  name = "Part 1"
  url = "/"
  identifier = "home"
  weight = -1
[[menu.main]]
  name = "Part 2"
  url = "/part-2/"
  identifier = "part-2"
  weight = 1