baseURL = "https://dgraph-twitter-clone-tutorial.netlify.com/"
languageCode = "en-us"
title = "Building a Twitter Clone with Dgraph and React"
theme = "hugo-docs"

[blackfriday]
  taskLists = false
  fencedCode = true

[[menu.main]]
  name = "Part 1: The Architecture"
  url = "/building-twitter-clone-with-dgraph-react-part-1-architecture"
  identifier = "building-twitter-clone-with-dgraph-react-part-1-architecture"
  weight = -1

[[menu.main]]
  name = "Part 2: The API"
  url = "/building-twitter-clone-with-dgraph-react-part-2-api"
  identifier = "building-twitter-clone-with-dgraph-react-part-2-api"
  weight = 1

[[menu.main]]
  name = "Part 3: The Client"
  url = "/building-twitter-clone-with-dgraph-react-part-3-client"
  identifier = "building-twitter-clone-with-dgraph-react-part-3-client"
  weight = 2