baseURL = "https://dgraph-twitter-clone-tutorial.netlify.com/"
languageCode = "en-us"
title = "Building a Twitter Clone with Dgraph and React"
theme = "hugo-docs"

[blackfriday]
  taskLists = false
  fencedCode = true

[[menu.main]]
  name        = "Part 1: The Architecture"
  url         = "/"
  identifier  = "home"
  weight      = -1
[[menu.main]]
  name = "Part 2: The API"
  url = "/part-2-api/"
  identifier = "part-2-api"
  weight = 1
[[menu.main]]
  name = "Part 3: The Client"
  url = "/part-3-client/"
  identifier = "part-3-client"
  weight = 2