baseURL = "https://dgraph-twitter-clone.pingpub.dev/"
languageCode = "en-us"
title = "Building a Twitter Clone with Dgraph and React"
theme = "hugo-docs"

[blackfriday]
  taskLists = false
  fencedCode = true

[[menu.main]]
  name        = "Twitter Clone with React"
  url         = "/"
  identifier  = "home"
  weight      = -1